### ISSUE TITLE
Keep track of commands as they are executing, and afterwards

### ISSUE THREAD

**Issue by omame** [pcarranza/meeseeks-box#11]
To allow checking what was executed when, and with which output, we should keep state of the executed commands, as they are started, and completed, and whenever a user wants to check the status.

This means that we need to add a set of builtin commands that enable to query commands like:

- status: (with id) returns the commands that are in flight right now. (or something like that, I can't think of a better command, honestly)
- status <id>: returns the status of a command, status can be `Running`, `Successful` and `Failed`
- output <id>: returns the execution message from the command, such that it prints the stdout/err if the command succeded or failed.

### Requirements

- We will need to keep track of the commands in some form of persistence for the command metadata, the best for this is sqlite for simplicity.
- We will need to keep track of the output of the commands, for this the best is simply the filesystem (as a first step) but they should be treated as a key/value store to allow future implementations to move these files to object storage.
- These commands should be allowed to Any, but limiting to their own commands, meaning that if the command they want to check is not theirs it should be a not allowed violation, unless the requester is an admin.

**Comment by pcarranza** [comment]
I think this one is done

**Comment by omame** [comment]
I think we're still missing the status for the commands that are currently in flight.

**Comment by pcarranza** [comment]
Not really, you can check it with `/last` and `/tail`

**Comment by omame** [comment]
What I meant is in https://github.com/pcarranza/meeseeks-box/pull/13 and https://github.com/pcarranza/meeseeks-box/pull/15.
I think we can close this.
